name: gl4u_rnaseq_2024
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10
  - pip
  - jupyterlab==4.2.5
  - notebook==6.5.5
  - bash_kernel==0.9.3
  - r-irkernel
  - coreutils
  - htslib
  - openssl
  - nodejs
  - r-base==4.4.1
  - r-biocmanager==1.30.25
  - r-tidyverse==2.0.0
  - r-ggfortify==0.4.17
  - r-ggnewscale==0.5.0
  - star==2.7.11b
  - cutadapt==4.9
  - trim-galore==0.6.10
  - fastqc==0.12.1
  - multiqc==1.24.1
  - samtools==1.21
  - pip:
    - jupyter_contrib_nbextensions==0.7.0
    - jupyter_nbextensions_configurator==0.6.3
    - nbclassic==0.4.8